# Generated by Django 4.0.2 on 2022-02-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('choose', models.CharField(max_length=200)),
            ],
        ),
    ]
